services:

  app-image:
    profiles:
      - ad-hoc
    image: caracolazuldev/docker-config-app
    build:
      context: .
      dockerfile: docker/config-app/Dockerfile
    volumes:
      - .:/go/src/app

  go-image:
    profiles:
      - ad-hoc
    image: caracolazuldev/go-dev
    build:
      context: docker/go-dev

  # app:
  #   image: caracolazuldev/go-dev
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - .:/go/src/app
  #   working_dir: /go/src/app

  go:
    image: caracolazuldev/go-dev
    user: go
    volumes:
      - .:/go/src/app/${APP_NAME:-docker-config-app-cli}
    working_dir: /go/src/app/${APP_NAME:-docker-config-app-cli}
    entrypoint: ["go"]
    command: ["build", "-C", "/go/src/app/${APP_NAME:-docker-config-app-cli}"]

  go-shell:
    image: caracolazuldev/go-dev
    user: go
    volumes:
      - .:/go/src/app/${APP_NAME:-docker-config-app-cli}
    working_dir: /go/src/app/${APP_NAME:-docker-config-app-cli}
    entrypoint: ["/bin/bash"]
    command: []