services:

  config-app:
    image: caracolazuldev/docker-config-app
    build:
      context: .
    volumes:
      - .:/go/src/app

  go-run:
    image: golang
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app

  go-build:
    image: golang
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/app
    entrypoint: ["go", "build"]
    command: ["-o", "/go/src/app/dist/${APP_NAME:-add-config}", "/go/src/app/${APP_NAME:-add-config}.go"]