services:

  app-image:
    profiles:
      - ad-hoc
    image: caracolazuldev/docker-config-app
    build:
      context: .
      dockerfile: docker/config-app/Dockerfile
    volumes:
      - .:/go/src/${APP_NAME:-docker-config-app-cli}

  go-image:
    profiles:
      - ad-hoc
    image: caracolazuldev/go-dev
    build:
      context: docker/go-dev

  # app:
  #   image: caracolazuldev/go-dev
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - .:/go/src/app
  #   working_dir: /go/src/app

  go:
    profiles:
      - ad-hoc
    image: caracolazuldev/go-dev
    user: go
    volumes:
      - go-wksp:/go
      - .:/go/src/app
    working_dir: /go/src/app

  dev:
    image: caracolazuldev/go-dev
    user: go
    volumes:
      - go-wksp:/go
      - .:/go/src/app
    working_dir: /go/src/app
    entrypoint: ["/bin/bash"]
    # keep the container running
    command: ["-c", "while true; do sleep 30; done"]

  mockery:
    profiles:
      - ad-hoc
    image: vektra/mockery:v2
    volumes:
      - go-wksp:/go
      - .:/go/src/app
    working_dir: /go/src/app

#  coming soon: requires Docker Compose 2.22.0
# (un-tested)
# requiers passing --watch to `docker compose up`
  # watch:
  #   image: caracolazuldev/go-dev
  #   user: go
  #   volumes:
  #     - go-wksp:/go
  #   working_dir: /go/src/app
  #   command: ["build"]
  #   develop:
  #     watch:
  #       - action: sync+restart
  #         path: .
  #         target: /go/src/app

  shell:
    image: caracolazuldev/go-dev
    profiles:
      - ad-hoc
    user: go
    volumes:
      - go-wksp:/go
      - .:/go/src/app
    working_dir: /go/src/app
    entrypoint: ["/bin/bash"]

  playground:
    image: x1unix/go-playground:latest
    restart: unless-stopped
    profiles:
      - ad-hoc
    ports:
      - 8000:8000
    environment:
      APP_CLEAN_INTERVAL: '30m'
    volumes:
      - .:/go/src/${APP_NAME:-docker-config-app-cli}

volumes:
  go-wksp:
