// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// iUser is an autogenerated mock type for the iUser type
type iUser struct {
	mock.Mock
}

// OnError provides a mock function with given fields: tpl, err
func (_m *iUser) OnError(tpl string, err error) {
	_m.Called(tpl, err)
}

// PrintLn provides a mock function with given fields: a
func (_m *iUser) PrintLn(a ...interface{}) (int, error) {
	var _ca []interface{}
	_ca = append(_ca, a...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PrintLn")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(...interface{}) (int, error)); ok {
		return rf(a...)
	}
	if rf, ok := ret.Get(0).(func(...interface{}) int); ok {
		r0 = rf(a...)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(a...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadLn provides a mock function with given fields: prompt
func (_m *iUser) ReadLn(prompt string) (string, error) {
	ret := _m.Called(prompt)

	if len(ret) == 0 {
		panic("no return value specified for ReadLn")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(prompt)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(prompt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(prompt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newIUser creates a new instance of iUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *iUser {
	mock := &iUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
